### ISSUE TITLE
Example of AsyncFunction please

### ISSUE THREAD

**Issue by darrenstarr** [nilproject/NiL.JS#113]
I've been integrating Nil.js as the scripting engine in my project and I would like to implement the ability to await return data from external operations.

Can you please provide a brief example/unit test of using AsyncFunction to call into C#?

I am hoping that I can call from my code something like :
```c#
function expectData() {
    return new Promise(resolve => remoteHost.expectData(resolve, "hello"));
  }
  
  async function demo() {
    var text = await expectData();
    console.log('Here comes the text: ' + text);
  }

  demo();
```

Where remoteHost is a C# object. I can implement async, begin/end, delegate driven... whatever.

Can you please provide an example which does this?

**Comment by nilproject** [comment]
Just return `Task` from `expectData`.
```CS
        private sealed class RemoveHost
        {
            public Task<string> expectData(object obj, string result)
            {
                var task = new Task<string>(() => result);
                task.Start();
                return task;
            }
        }

        static void Main(string[] args)
        {
            var context = new Context();
            context.DefineVariable("remoteHost").Assign(new RemoveHost());
            context.Eval(@"
function expectData() {
    return remoteHost.expectData(null, ""hello"");
}

async function demo() {
    var text = await expectData();
    console.log('Here comes the text: ' + text);
}

demo();");
            Console.ReadLine();
        }
```
All `Task` wraps into `Promise` for JS environment.

But I found some bug that did not allow to write constructions like
```JS
var text = await expectData();
```
Update you copy of source code from branch `develop` or use `Promise.then(...)` until when I updates the nuget package.

**Comment by nilproject** [comment]
I updated the package.

**Comment by bilenkonito** [comment]
This does not seem to work inside modules.

```javascript
export default class PepeScene {
	constructor() {
		console.log('Hello from Pepe');
		tester();
	}
	async tester() {
		let texture = new TestExportClass("test_spritesheet");
		console.log(JSON.stringify(texture));
		console.log(await texture.IsActive());
		await texture.Activate();
		console.log(await texture.IsActive());
		await texture.Deactivate();
		console.log(await texture.IsActive());
		console.log(await texture.Active);
	}
}
```

```
System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> NiL.JS.Core.JSException: SyntaxError: Unknown identifier "tester()" at (7:8)
   at NiL.JS.ExceptionHelper.Throw(Error error)
   at NiL.JS.ExceptionHelper.ThrowUnknownToken(String code, Int32 index)
   at NiL.JS.Expressions.FunctionDefinition.Parse(ParseInfo state, Int32& index, FunctionKind kind)
   at NiL.JS.Expressions.ClassDefinition.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Statements.ExportStatement.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet)
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Script.Parse(String code, CompilerMessageCallback messageCallback, Options options)
   at NiL.JS.Module..ctor(String virtualPath, String code, CompilerMessageCallback messageCallback, Options options)
   at NiL.JS.Module..ctor(String path, String code)
```
