### ISSUE TITLE
Exception assigning interpolation function

### ISSUE THREAD

**Issue by jsobell** [nilproject/NiL.JS#142]
```js
var func = (x) => `This returns ${x}`;
func('Fred');
```
Throws
```text
System.NullReferenceException: Object reference not set to an instance of an object.
   at NiL.JS.Core.VariableDescriptor.Get(Context context, Boolean forWrite, Int32 scopeLevel)
   at NiL.JS.Expressions.Variable.Evaluate(Context context)
   at NiL.JS.Expressions.TemplateString.Evaluate(Context context)
   at NiL.JS.Expressions.FunctionDefinition.MakeFunction(Context context)
   at NiL.JS.Expressions.FunctionDefinition.Evaluate(Context context)
   at NiL.JS.Expressions.SetProperty.safeGet(JSValue temp, CodeNode source, Context context)
   at NiL.JS.Expressions.SetProperty.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation)
   at NiL.JS.Core.Context.Eval(String code, Boolean suppressScopeCreation)
   at NiL.JS.Core.Context.Eval(String code)
   at FunctionalTests.StringInterpolationTests.StringInterpolationAllowsFunctions() in D:\GitHub\NiL.JS.QM\FunctionalTests\StringInterpolationTests.cs:line 28
```

It looks like the interpolation expression is being evaluated (and the context is null, and 'x' undefined), which obviously shouldn't be happening.

**Comment by nilproject** [comment]
Thanks for this bug report!
