### ISSUE TITLE
"Invalid Variable Name" on exports

### ISSUE THREAD

**Issue by Nikey646** [nilproject/NiL.JS#147]
Whenever you try to load a file that has a export for a variable, it causes an `ArgumentException` with "Invalid Variable Name"

The js code: 
```js
import { assignIn } from 'node_modules/lodash-es/assignIn.js'

const options = {
	foo: 'bar',
	bar: 'Failed',
}
const otherOptions = {
	bar: 'foo',
}

export default _.extend(options, otherOptions)
```

I'm fairly sure this stack trace is from trying to load the lodash-es package, but the file has an `export default assignIn` with `assignIn` being a variable.
```
   at NiL.JS.Expressions.Variable..ctor(String name, Int32 scopeLevel)
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Statements.ExportStatement.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Module..ctor(String path, String code, CompilerMessageCallback messageCallback, Options options)
   at NiL.JS.Module..ctor(String path, String code)
   at TestConsole.Program.TypescriptResolver(Module sender, ResolveModuleEventArgs e) in C:\Projects\CSharp\Mangado\Engines\Mangado.Engine.Js\src\TestConsole\Program.cs:line 59
   at NiL.JS.Module.Import(String path)
   at NiL.JS.Statements.ImportStatement.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Module.Run()
   at TestConsole.Program.TypescriptResolver(Module sender, ResolveModuleEventArgs e) in C:\Projects\CSharp\Mangado\Engines\Mangado.Engine.Js\src\TestConsole\Program.cs:line 60
   at NiL.JS.Module.Import(String path)
   at NiL.JS.Statements.ImportStatement.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Module.Run()
   at TestConsole.Program.Main(String[] args)
``` 

C# code is just a simple `new Module('path', 'contents').Run()` with a simple file loader that grabs the specified .js file from the disk.

According to MDN, this should be possible?

**Comment by nilproject** [comment]
Thanks for this bug report!
