### ISSUE TITLE
Regular expression parsing error

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#160]
Hello, Dmitry!

When parsing a `[^]*?(:[rp][el]a[\w-]+)[^]*` regular expression, the following error occurs:

```
NiL.JS.Core.JSException: SyntaxError: parsing '[^]*?(:[rp][el]a[\w-]+)[^]*' - Unterminated [] set.
   at NiL.JS.ExceptionHelper.Throw(Error error)
   at NiL.JS.BaseLibrary.RegExp.makeRegex(String pattern, String flags)
   at NiL.JS.Expressions.RegExpExpression.Evaluate(Context context)
   at NiL.JS.Expressions.Assignment.Evaluate(Context context)
   at NiL.JS.Statements.VariableDefinition.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation)
   at TestNilJs.Program.Main(String[] args) in C:\Projects\!EXPERIMENTAL\NiL.JS\TestNilJs\TestNilJs\Program.cs:line 12
```
This error does not occur in the latest versions of V8 and ChakraCore, but is also typical for Jurassic and Jint.

You can use the following C#-code to reproduce the error:

```csharp
using System;

using NiL.JS.Core;

namespace TestNilJs
{
    class Program
    {
        static void Main(string[] args)
        {
            const string code = @"var na = /[^]*?(:[rp][el]a[\w-]+)[^]*/;";
            var context = new Context(true);

            try
            {
                context.Eval(code);
            }
            catch (JSException e)
            {
                Console.Write(e.ToString());
            }
        }
    }
}
```

**Comment by nilproject** [comment]
Hello, Andrey!
Yes, it's known bug. It's because I used `System.Text.RegularExpressions`, which is not fully compatible with JavaScript RegExp.

**Comment by Taritsyn** [comment]
OK. Looks like that this issue needs to be sent to Microsoft.
