### ISSUE TITLE
Minified JS code parsing error

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#161]
Hello, Dmitry!

When parsing a minified JS code:

```js
var obj = Object.setPrototypeOf || ('__proto__'in{}?function(t, r, i) {
	try {
		i = e(31)(Function.call, n(Object.prototype, '__proto__').set, 2), i(t, []), r = !(t instanceof Array)
	} catch (s) {
		r = !0
	}
	return function(e, t) {
		return a(e, t), r ? e.__proto__ = t : i(e, t), e
	}
}({}, !1) : void 0)
```

Following error occurs:

```
NiL.JS.Core.JSException: SyntaxError: Unexpected token (1:51)
   at NiL.JS.ExceptionHelper.Throw(Error error)
   at NiL.JS.ExceptionHelper.ThrowSyntaxError(String message, String code, Int32 position)
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.parseContinuation(ParseInfo state, Expression first, Int32 startIndex, Int32& i, Boolean& root, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.parseContinuation(ParseInfo state, Expression first, Int32 startIndex, Int32& i, Boolean& root, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.parseContinuation(ParseInfo state, Expression first, Int32 startIndex, Int32& i, Boolean& root, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Statements.VariableDefinition.Parse(ParseInfo state, Int32& index, Boolean forForLoop)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation)
   at TestNilJs.Program.Main(String[] args) in C:\Projects\!EXPERIMENTAL\NiL.JS\TestNilJs\TestNilJs\Program.cs:line 21
```

This error does not occur in V8, ChakraCore, Jurassic and Jint.

You can use the following C#-code to reproduce the error:

```csharp
using System;

using NiL.JS.Core;

namespace TestNilJs
{
    class Program
    {
        static void Main(string[] args)
        {
            const string code = @"var obj = Object.setPrototypeOf || ('__proto__'in{}?function(t, r, i) {
    try {
        i = e(31)(Function.call, n(Object.prototype, '__proto__').set, 2), i(t, []), r = !(t instanceof Array)
    } catch (s) {
        r = !0
    }
    return function(e, t) {
        return a(e, t), r ? e.__proto__ = t : i(e, t), e
    }
}({}, !1) : void 0)";
            var context = new Context(true);

            try
            {
                context.Eval(code);
            }
            catch (JSException e)
            {
                Console.Write(e.ToString());
            }
        }
    }
}
```

**Comment by nilproject** [comment]
Thanks for this bugreport! It's very strange that this bug was not caught many years ago. It exist since very first version.

**Comment by Taritsyn** [comment]
Thank you! I found this error when working with the [ReactJS.NET](https://github.com/reactjs/React.NET) library. After a while I will describe the errors that occur in the [Bundle Transformer](https://github.com/Taritsyn/BundleTransformer) library. In general, I will try to fulfill the promise made in [my article](https://habr.com/ru/post/439446/).

**Comment by nilproject** [comment]
Wow! Thanks for mentioning my engine!
