### ISSUE TITLE
Other error during parsing minified JS code

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#162]
Hello, Dmitry!

When parsing a minified JS code in latest version of NiL.JS (built from the [`af3a795`](https://github.com/nilproject/NiL.JS/tree/af3a795e4f3db55ecb88b674b9aaf1cc96e7aa2b) commit):

```js
var arr = ['a', 'b', 'c'],
    num = 0
    ;

if (arr.length > 1)
    for (var i = 0; i < arr.length; i++)
        if (arr[i] == 'a') num += 12;
        else if (arr[i] == 'b') num += 5;
        else break;else num = -1;
```

Following error occurs:

```
NiL.JS.Core.JSException: SyntaxError: Unknown identifier "else" at (9:14)
   at NiL.JS.ExceptionHelper.Throw(Error error) in C:\temp\NiL.JS-develop\NiL.JS\ExceptionHelper.cs:line 21
   at NiL.JS.ExceptionHelper.ThrowUnknownToken(String code, Int32 index) in C:\temp\NiL.JS-develop\NiL.JS\ExceptionHelper.cs:line 107
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 0
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation) in C:\temp\NiL.JS-develop\NiL.JS\Core\Context.cs:line 628
   at TestNilJs.Program.Main(String[] args) in C:\Projects\!EXPERIMENTAL\NiL.JS\TestNilJs\TestNilJs\Program.cs:line 20
```

This error does not occur in V8, ChakraCore, Jurassic and Jint.

You can use the following C#-code to reproduce the error:

```csharp
using System;

using NiL.JS.Core;

namespace TestNilJs
{
    class Program
    {
        static void Main(string[] args)
        {
            const string code = @"var arr = ['a', 'b', 'c'],
    num = 0
    ;

if (arr.length > 1)
    for (var i = 0; i < arr.length; i++)
        if (arr[i] == 'a') num += 12;
        else if (arr[i] == 'b') num += 5;
        else break;else num = -1;";
            var context = new Context(true);

            try
            {
                context.Eval(code);
            }
            catch (JSException e)
            {
                Console.Write(e.ToString());
            }
        }
    }
}
```

**Comment by nilproject** [comment]
Thanks, Andrey!

**Comment by Taritsyn** [comment]
Thank you!
