### ISSUE TITLE
Non-standard parsing error in strict mode

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#163]
Hello, Dmitry!

When parsing a JS code in strict mode (NiL.JS built from the [`af3a795`](https://github.com/nilproject/NiL.JS/tree/af3a795e4f3db55ecb88b674b9aaf1cc96e7aa2b) commit):

```js
'use strict';

function cr(n, t, i, r, u) {
    var o;
    if (n && n.length > 0 && (o = n.length, o > 0)) {
        var f = r === undefined || r < 0 ? 0 : r,
            s = u === undefined || f + u > o - 1 ? o - 1 : f + u,
            e = void 0;
        for (arguments.length <= 2 ? (e = n[f], f++) : e = i; f <= s;) e = t(e, n[f], f), f++;
        return e
    }
    return i
}
```

Following error occurs:

```
NiL.JS.Core.JSException: SyntaxError: Parameters name may not be "arguments" or "eval" in strict mode at  (9:8)
   at NiL.JS.ExceptionHelper.Throw(Error error) in C:\temp\NiL.JS-develop\NiL.JS\ExceptionHelper.cs:line 21
   at NiL.JS.Statements.ForOf.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\ForOf.cs:line 89
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 760
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 760
   at NiL.JS.Statements.IfElse.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\IfElse.cs:line 46
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 760
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Expressions.FunctionDefinition.Parse(ParseInfo state, Int32& index, FunctionKind kind) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\FunctionDefinition.cs:line 428
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 760
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation) in C:\temp\NiL.JS-develop\NiL.JS\Core\Context.cs:line 628
   at TestNilJs.Program.Main(String[] args) in C:\Projects\!EXPERIMENTAL\NiL.JS\TestNilJs\TestNilJs\Program.cs:line 24
```

This error does not occur in V8, ChakraCore, Jurassic and Jint.

You can use the following C#-code to reproduce the error:

```csharp
using System;

using NiL.JS.Core;

namespace TestNilJs
{
    class Program
    {
        static void Main(string[] args)
        {
            const string code = @"'use strict';

function cr(n, t, i, r, u) {
    var o;
    if (n && n.length > 0 && (o = n.length, o > 0)) {
        var f = r === undefined || r < 0 ? 0 : r,
            s = u === undefined || f + u > o - 1 ? o - 1 : f + u,
            e = void 0;
        for (arguments.length <= 2 ? (e = n[f], f++) : e = i; f <= s;) e = t(e, n[f], f), f++;
        return e
    }
    return i
}";
            var context = new Context();

            try
            {
                context.Eval(code);
            }
            catch (JSException e)
            {
                Console.Write(e.ToString());
            }
        }
    }
}
```

**Comment by nilproject** [comment]
Thanks, Andrey!

**Comment by Taritsyn** [comment]
Thank you!
