### ISSUE TITLE
Deprecated parsing error in strict mode

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#164]
Hello, Dmitry!

When parsing a JS code in strict mode (NiL.JS built from the [`3bfe2ee`](https://github.com/nilproject/NiL.JS/tree/3bfe2ee17033b8306bce3c460e2f2e7d07a33b2d)):

```js
var mathFunctions = {
    cube: function (num) {
        var result;

        if (num !== 0) {
            function square(n) {
                return n * n;
            }

            result = square(num) * num;
        }
        else {
            result = 0;
        }

        return result;
    }
};
```

Following error occurs:

```
NiL.JS.Core.JSException: SyntaxError: In strict mode code, functions can only be declared at top level or immediately within other function. (8:4)
   at NiL.JS.ExceptionHelper.Throw(Error error) in C:\temp\NiL.JS-develop\NiL.JS\ExceptionHelper.cs:line 21
   at NiL.JS.ExceptionHelper.ThrowSyntaxError(String message, String code, Int32 position) in C:\temp\NiL.JS-develop\NiL.JS\ExceptionHelper.cs:line 125
   at NiL.JS.Expressions.FunctionDefinition.Parse(ParseInfo state, Int32& index, FunctionKind kind) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\FunctionDefinition.cs:line 605
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 761
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 761
   at NiL.JS.Statements.IfElse.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\IfElse.cs:line 53
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 761
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Expressions.FunctionDefinition.Parse(ParseInfo state, Int32& index, FunctionKind kind) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\FunctionDefinition.cs:line 428
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 761
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ExpressionTree.cs:line 1101
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ExpressionTree.cs:line 325
   at NiL.JS.Expressions.ObjectDefinition.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ObjectDefinition.cs:line 261
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 761
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ExpressionTree.cs:line 1101
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ExpressionTree.cs:line 325
   at NiL.JS.Expressions.ExpressionTree.parseContinuation(ParseInfo state, Expression first, Int32 startIndex, Int32& i, Boolean& root, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ExpressionTree.cs:line 978
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Expressions\ExpressionTree.cs:line 329
   at NiL.JS.Statements.VariableDefinition.Parse(ParseInfo state, Int32& index, Boolean forForLoop) in C:\temp\NiL.JS-develop\NiL.JS\Statements\VariableDefinition.cs:line 77
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\temp\NiL.JS-develop\NiL.JS\Core\Parser.cs:line 761
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index) in C:\temp\NiL.JS-develop\NiL.JS\Statements\CodeBlock.cs:line 170
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation) in C:\temp\NiL.JS-develop\NiL.JS\Core\Context.cs:line 628
   at TestNilJs.Program.Main(String[] args) in C:\Projects\!EXPERIMENTAL\NiL.JS\TestNilJs\TestNilJs\Program.cs:line 31
```

This error does not occur in V8, ChakraCore, Jurassic and Jint. A similar error occurs only in the [Vroom](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Vroom) module that is based on a very old version of the V8 engine (version 3.17.16.2).

You can use the following C#-code to reproduce the error:

```csharp
using System;

using NiL.JS.Core;

namespace TestNilJs
{
    class Program
    {
        static void Main(string[] args)
        {
            const string code = @"'use strict';

var mathFunctions = {
    cube: function (num) {
        var result;

        if (num !== 0) {
            function square(n) {
                return n * n;
            }

            result = square(num) * num;
        }
        else {
            result = 0;
        }

        return result;
    }
};";
            var context = new Context();

            try
            {
                context.Eval(code);
            }
            catch (JSException e)
            {
                Console.WriteLine(e.ToString());
            }
        }
    }
}
```

**Comment by nilproject** [comment]
Thanks, Andrey!

**Comment by Taritsyn** [comment]
Thanks, Dmitry!
