### ISSUE TITLE
Error evaluating decimal.js

### ISSUE THREAD

**Issue by pierom99** [nilproject/NiL.JS#172]
After upgrading from 2.5.1294 to 2.5.1320 i get a failed test:
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at NiL.JS.Core.Parser.ValidateArrow(String code, Int32 index) in C:\Users\???????\Documents\Visual Studio 2017\Projects\NiL.JS\nil.js\Core\Parser.cs:line 137
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError) in C:\Users\???????\Documents\Visual Studio 2017\Projects\NiL.JS\nil.js\Core\Parser.cs:line 776
My code is:
            var scriptJS = File.ReadAllText(_testContentFiles + "\\decimal.js");
            _jsNIL.Context.Eval(scriptJS);

**Comment by nilproject** [comment]
Thanks for this bugreport!
