### ISSUE TITLE
Async functions don't work inside Classes.

### ISSUE THREAD

**Issue by bilenkonito** [nilproject/NiL.JS#174]
Async methods don't work inside classes, I suppose because you're not allowed to use the keyword "function" there and "FunctionDefinition" seems to be checking for it.

```javascript
export default class PepeScene {
	constructor() {
		console.log('Hello from Pepe');
		tester();
	}
	async tester() {
		let texture = new TestExportClass("test_spritesheet");
		console.log(JSON.stringify(texture));
		console.log(await texture.IsActive());
		await texture.Activate();
		console.log(await texture.IsActive());
		await texture.Deactivate();
		console.log(await texture.IsActive());
		console.log(await texture.Active);
	}
}
```

```
System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> NiL.JS.Core.JSException: SyntaxError: Unknown identifier "tester()" at (7:8)
   at NiL.JS.ExceptionHelper.Throw(Error error)
   at NiL.JS.ExceptionHelper.ThrowUnknownToken(String code, Int32 index)
   at NiL.JS.Expressions.FunctionDefinition.Parse(ParseInfo state, Int32& index, FunctionKind kind)
   at NiL.JS.Expressions.ClassDefinition.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
   at NiL.JS.Expressions.ExpressionTree.parseOperand(ParseInfo state, Int32& i, Boolean forNew, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index, Boolean forUnary, Boolean processComma, Boolean forNew, Boolean root, Boolean forForLoop)
   at NiL.JS.Expressions.ExpressionTree.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Statements.ExportStatement.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet, Boolean throwError)
   at NiL.JS.Core.Parser.Parse(ParseInfo state, Int32& index, CodeFragmentType ruleSet)
   at NiL.JS.Statements.CodeBlock.Parse(ParseInfo state, Int32& index)
   at NiL.JS.Script.Parse(String code, CompilerMessageCallback messageCallback, Options options)
   at NiL.JS.Module..ctor(String virtualPath, String code, CompilerMessageCallback messageCallback, Options options)
   at NiL.JS.Module..ctor(String path, String code)
```

**Comment by bilenkonito** [comment]
I took a further look into "FunctionDefinition.cs" and it turns out that methods are eventually redirected to the "FunctionKind.Arrow" case when parsing, which don't take async into consideration.

@nilproject Please advise.

**Comment by nilproject** [comment]
At the time of implementation of async/await support these keywords was not allowed for class functions by JS standard. So, at the current time this implementation is outdated. I will fix it.
