### ISSUE TITLE
Error during rendering of Handlebars template

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#196]
Hello, Dmitry!

During rendering of Handlebars template the following error occurs:

```
NiL.JS.Core.JSException: TypeError: Can't set property "decorator" of "undefined"
   at NiL.JS.Core.Functions.MethodProxy.invokeMethod(JSValue targetValue, Expression[] argumentsSource, Arguments argumentsObject, Context initiator)
   at NiL.JS.Core.Functions.MethodProxy.InternalInvoke(JSValue targetValue, Expression[] argumentsSource, Context initiator, Boolean withSpread, Boolean withNew)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.Return.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.BaseLibrary.Function.Invoke(Boolean construct, JSValue targetObject, Arguments arguments)
   at NiL.JS.BaseLibrary.Function.Call(JSValue targetObject, Arguments arguments)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation)
```

To reproduce this error, I created a [demo project](https://www.dropbox.com/s/gz3fobm6u9uqdqy/TestHandlebarsRenderingInNiL.zip?dl=1). The same code works in all modern JS engines and even in the Microsoft JScript.

**Comment by nilproject** [comment]
Thanks for this bug report, Andrey!

**Comment by Taritsyn** [comment]
Thank you very much!
