### ISSUE TITLE
[BUG] JSException: TypeError: Can not call function "{property_setter}" for object of another type

### ISSUE THREAD

**Issue by Markeli** [nilproject/NiL.JS#228]
We compiled the dll from the last commit from develop branch and used it on the production. And after this update, a lot of exceptions were thrown.

```csharp
Can not call function "set_flags" for object of another type.
SIISLtd.SSNG.Core.Scripting.ScriptErrorException: Ошибка при выполнении скрипта "Подготовка" в строке 62 (символ 31): TypeError: Can not call function "set_flags" for object of another type. ---> NiL.JS.Core.JSException: TypeError: Can not call function "set_flags" for object of another type.
at NiL.JS.ExceptionHelper.Throw(Error error)
at NiL.JS.Core.Functions.MethodProxy.GetTargetObject(JSValue targetValue, Object hardTarget)
at NiL.JS.Core.Functions.MethodProxy.invokeMethod(JSValue targetValue, Expression[] argumentsSource, Arguments argumentsObject, Context initiator)
at NiL.JS.Core.Functions.MethodProxy.Invoke(Boolean construct, JSValue targetObject, Arguments arguments)
at NiL.JS.BaseLibrary.Function.Call(JSValue targetObject, Arguments arguments)
at NiL.JS.Expressions.Assignment.setProperty(Context context, JSValue field, JSValue value)
at NiL.JS.Statements.IfElse.Evaluate(Context context)
at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
at NiL.JS.BaseLibrary.Function.Invoke(Boolean construct, JSValue targetObject, Arguments arguments)
at NiL.JS.BaseLibrary.Function.Call(JSValue targetObject, Arguments arguments)
```
There were problems with calling property setter. 

We added our class to context as variable:

```csharp
context
   .DefineVariable("Q")
   .Assign(new JSQuestion(_SurveyData.Questions));
``` 

JSQuestion is our custom type:

```chsarp
public class JSQuestion : CustomType
{
   public int flags { get; set; }
   public string outputColumnTemplateOVN { get;set; }
}
```

![image](https://user-images.githubusercontent.com/5919274/89027727-af88ea80-d333-11ea-9750-d01488ac75be.png)

But when we rolled backed to NiL.JS from NuGet (`v 2.5.1419`) everything was fine.  No changes to our code or scripts were made.

**Comment by nilproject** [comment]
So, this was a bug that this (look as) worked before. There is no support for `Enum`s with native syntax.

**Comment by nilproject** [comment]
I pushed new build.

**Comment by Markeli** [comment]
Thanks!
