### ISSUE TITLE
Compile error with typescript  v4.5.2

### ISSUE THREAD

**Issue by viceice** [nilproject/NiL.JS#269]
Since #268 is fixed, i've now trying to do the same with the new ts version at https://github.com/viceice/dotnet-ts-testing/pull/177.

it fails with
```
NiL.JS.Core.JSException: Error: Can't get property ""length"" of "undefined"
   at NiL.JS.ExceptionHelper.Throw(JSValue error)
   at NiL.JS.Statements.Throw.Evaluate(Context context)
   at NiL.JS.Statements.TryCatch.<>c__DisplayClass16_0.<catchHandler>b__0(Context c)
   at NiL.JS.Statements.TryCatch.catchHandler(Context context, Exception e)
   at NiL.JS.Statements.TryCatch.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.BaseLibrary.Function.Invoke(Boolean construct, JSValue targetObject, Arguments arguments)
   at NiL.JS.BaseLibrary.Function.Call(JSValue targetObject, Arguments arguments)
   at dotnet_ts_testing.Engines.NilJsEngine.Compile(String code) in /home/runner/work/dotnet-ts-testing/dotnet-ts-testing/Engines/NilJsEngine.cs:line 15
   at dotnet_ts_testing.Engines.JsEngine.Test(String test) in /home/runner/work/dotnet-ts-testing/dotnet-ts-testing/Engines/JsEngine.cs:line 61
```

Here is a gist of the js file with fails: https://gist.github.com/viceice/923c5b995bc26fbf8194151109a2c91b

**Comment by nilproject** [comment]
116 lines in `Map.cs`, but so many bugs.
Thanks for your bug report. And your test app, it was very useful in investigation of this bug

**Comment by viceice** [comment]
When this will be released? 🙃

**Comment by nilproject** [comment]
Uploaded

**Comment by viceice** [comment]
Thank you
