### ISSUE TITLE
NullReferenceException instead of the JSException during a calling of embedded delegate with missing parameter

### ISSUE THREAD

**Issue by Taritsyn** [nilproject/NiL.JS#280]
Hello, Dmitry!

In NiL.JS version 2.5.1591 during a calling of embedded delegate with missing parameter, the following unexpected exception is thrown:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at <Main>b__0_0(Closure , Object , Context , Expression[] , Arguments )
   at NiL.JS.Core.Functions.MethodProxy.invokeMethod(JSValue targetValue, Expression[] argumentsSource, Arguments argumentsObject, Context initiator)
   at NiL.JS.Core.Functions.MethodProxy.InternalInvoke(JSValue targetValue, Expression[] argumentsSource, Context initiator, Boolean withSpread, Boolean withNew)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Core.Context.doEval(CodeBlock body, Context context)
   at NiL.JS.Core.Context.Eval(String code, JSValue thisBind, Boolean suppressScopeCreation)
   at NiL.JS.Core.Context.Eval(String code, Boolean suppressScopeCreation)
   at TestNiL.Program.Main(String[] args) in D:\Temp\TestNiL\TestNiL\Program.cs:line 19
```

There were no such error in version 2.5.1560. To reproduce this error, I created a example:

```csharp
using System;

using NiL.JS.Core;

namespace TestNiL
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var sumFunc = new Func<int, int, int>((a, b) => a + b);

            var context = new Context();
            JSValue variableValue = context.DefineVariable("sum", true);
            variableValue.Assign(JSValue.Marshal(sumFunc));

            try
            {
                context.Eval("sum(678)", true);
            }
            catch (JSException e)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("Success!");

                Console.WriteLine();

                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("Expected error: {0}", e.ToString());
            }
            catch (NullReferenceException e)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Failed!");

                Console.WriteLine();

                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("Unexpected error: {0}", e.ToString());
            }
        }
    }
}
```

**Comment by nilproject** [comment]
Thanks for this bug report. I found this bug too, but after the release. As I understand, this bug had been for a long time, but hidden with try-catch around wrapper call and now become visible. I guess this code should not to throw an exception, but use a default value of type of parameter. At least, this happens when parameter is of reference type. But i'm not sure

**Comment by Taritsyn** [comment]
Hello, Dmitry!

> I guess this code should not to throw an exception, but use a default value of type of parameter.

Jint and Jurassic use a default value of type of parameter, but Microsoft ClearScript.V8 and Chakra .NET wrappers throw their own exception.

**Comment by Taritsyn** [comment]
Thanks!
