### ISSUE TITLE
Yield operator bug.

### ISSUE THREAD

**Issue by Chamberlain91** [nilproject/NiL.JS#57]
Hello again, using the NuGet copy:

```
function* anotherGenerator(i) {
    yield 0;
    yield i + 1;
}

function* generator(i) {
    yield i;
    yield* anotherGenerator();
}

let co = generator(1);

let it = null;
do {
    it = co.next();
    if( !it.done )
        console.log( it.value );
} 
while( !it.done );
```

Throws a NotImplementedException for the line `yield i + 1;`

```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at NiL.JS.Expressions.Addition.Decompose(Expression& self, IList`1 result)
   at NiL.JS.Expressions.Yield.Decompose(Expression& self, IList`1 result)
   at NiL.JS.Expressions.Expression.Decompose(CodeNode& self)
   at NiL.JS.Statements.CodeBlock.Decompose(CodeNode& self)
   at NiL.JS.Expressions.FunctionDefinition.Decompose(Expression& self, IList`1 result)
   at NiL.JS.Expressions.Expression.Decompose(CodeNode& self)
   at NiL.JS.Statements.CodeBlock.Decompose(CodeNode& self)
   at NiL.JS.Core.Context.Eval(String code, Boolean inplace)
   at NiL.JS.Core.Context.Eval(String code)
   ...
```

**Comment by nilproject** [comment]
Thank for this bug report!
