### ISSUE TITLE
Task => Promise

### ISSUE THREAD

**Issue by Wassili-Hense** [nilproject/NiL.JS#77]
Доброго времени суток Дмитрий,
пытаюсь разобраться с Promise.
```C#:
//C#
_self["TwiReq"] = JSValue.Marshal(new Func<int[], Task<JSValue>>(TwiReq));

Task<JSC.JSValue> TwiReq(int[] arr) {
  tsc = new TaskCompletionSource<JSValue>();
  // ...
  return tsc.Task;
}
```

```JS
//JS
this.TwiReq([ ... ]).then(SuccessFunc, ErrorFunc);
```
```C#:
//C#
tsc.SetResult(...); // работает правильно
tsc.SetException(new Exception("tra-la-la")); //до ErrorFunc дело не доходит
```
Как сделать правильно?

**Comment by nilproject** [comment]
Вы всё делаете правильно. Это была моя ошибка.

**Comment by Wassili-Hense** [comment]
Попробовал на версии из репозитария, вылетает с unhandled Exception:
```
System.Reflection.TargetInvocationException was unhandled by user code
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
       at NiL.JS.Core.GlobalContext.<>c__DisplayClass18_0.<ProxyValue>b__0() in NiL.JS\Core\GlobalContext.cs:line 466
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: 
       HResult=-2146233088
       Message=One or more errors occurred.
       Source=mscorlib
       StackTrace:
            at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       InnerException: 
            HResult=-2146233088
            Message=3
            InnerException: 
```
Состояние:
```
value	Id = 54, Status = Faulted, Method = "{null}", Result = "{Not yet computed}"	object {System.Threading.Tasks.Task<NiL.JS.Core.JSValue>}
value.Exception	Count = 1	System.Exception {System.AggregateException}
value.Exception.InnerException	{"3"}	System.Exception {NiL.JS.Core.JSException}
```

**Comment by nilproject** [comment]
Судя по сообщению об ошибке, оно работает, но тип исключения не тот. Попробуйте с новым исправлением.
