### ISSUE TITLE
try to load typescript.js

### ISSUE THREAD

**Issue by windischb** [nilproject/NiL.JS#80]
HI!

I'll get an Error if i try to load the typescript library...

If i use the "normal" typescript.js i'll get:
 'Item already Exists'.

With a minified version i'll get :
SyntaxError: Unknown identifier "&&(a.isBindingPattern(b.name)?f(b.name):(p(t,b.nam" at (1:968559)

Have you ever successfully load the typescript library?

**Comment by nilproject** [comment]
Thank for these bugs. I fixed first of them – from now "normal" typescript.js should works correctly.

**Comment by nilproject** [comment]
I fixed another bug with typescript.js. I cannot reproduce second bug.

**Comment by viceice** [comment]
I also trying to load typescript, see https://github.com/ViceIce/dotnet-ts-testing

I get a `NullReferenceException` when trying to run `ts.transpileModule`

You can use my repo to reproduce / test.

**Comment by nilproject** [comment]
@ViceIce, thanks for this bugreport and repro!

So definitely my engine is slower than V8
```
dotnet ts converter
[V8] Test test started ...
----------------------------------
typescript v3.7.4
compiling
----------------------------------
[V8] Test test succeeded in 00:00:00.6300376
----------------------------------
[Chakra] Test test started ...
----------------------------------
typescript v3.7.4
compiling
----------------------------------
[Chakra] Test test succeeded in 00:00:00.5763369
----------------------------------
[NiL.JS] Test test started ...
----------------------------------
typescript v3.7.4
compiling
----------------------------------
[NiL.JS] Test test succeeded in 00:00:04.4570263
----------------------------------
```

**Comment by viceice** [comment]
Nice, speed is currently not my problem 😅 . Until now I'm using Jint 3 beta, but a lot ES6 parts are missing and typescript is not working there, so i looked for alternates. Hopefully performance is enough. 

I also have some com interop parts in my real application, so i think i would get some trouble in chakra / v8.

**Comment by viceice** [comment]
@nilproject When do you plan to release the fix?

**Comment by nilproject** [comment]
@ViceIce Uploaded. Will be allowed soon. Build number is 1403

**Comment by viceice** [comment]
New problem, when i use minimized version.

See updated test repo for reproducing.

```
NiL.JS.Core.JSException: Error: e is not a function
   at NiL.JS.ExceptionHelper.Throw(JSValue error)
   at NiL.JS.Statements.Throw.Evaluate(Context context)
   at NiL.JS.Statements.TryCatch.<>c__DisplayClass16_0.<catchHandler>b__0(Context c)
   at NiL.JS.Statements.TryCatch.catchHandler(Context context, Exception e)
   at NiL.JS.Statements.TryCatch.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.BaseLibrary.Function.Invoke(Boolean construct, JSValue targetObject, Arguments arguments)
   at NiL.JS.BaseLibrary.Function.Call(JSValue targetObject, Arguments arguments)
   at NiL.JS.BaseLibrary.Function.InternalInvoke(JSValue targetObject, Expression[] arguments, Context initiator, Boolean withSpread, Boolean construct)
   at NiL.JS.Core.Functions.SimpleFunction.InternalInvoke(JSValue targetObject, Expression[] arguments, Context initiator, Boolean withSpread, Boolean construct)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.Return.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.BaseLibrary.Function.Invoke(Boolean construct, JSValue targetObject, Arguments arguments)
   at NiL.JS.BaseLibrary.Function.Call(JSValue targetObject, Arguments arguments)
   at NiL.JS.BaseLibrary.Function.Call(Arguments args)
```
